# Site settings (modified to fit Whiteglass expectations for site.vars)
title: Lambda reflections
author: Fotis Koutoulakis
description: >- # this means to ignore newlines until "baseurl:"
  Functional Programming, Proofs, Bioinformatics and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: en-GB
timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - .gitignore

# Social media (for Whiteglass)
twitter_username: NlightNFotis
comments: false

# Whiteglass theme configuration
theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Conversion (these form part of the default configuration, but it helps me
# to have them listed here explicitly)
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM  # Github-Flavoured Markdown
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
excerpt_separator: "<!-- more -->"
